"""create database

Revision ID: 51937c40cb46
Revises: 12d5e8a5dbdc
Create Date: 2026-03-28 21:48:00.422908

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "51937c40cb46"
down_revision: Union[str, Sequence[str], None] = "12d5e8a5dbdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
