"""remove static tables

Revision ID: 9db67c02ad72
Revises: 5db306c69cef
Create Date: 2026-03-28 23:07:37.529100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db67c02ad72'
down_revision: Union[str, Sequence[str], None] = '5db306c69cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_about_us_id'), table_name='about_us')
    op.drop_table('about_us')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.alter_column('sliders', 'description_uz',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sliders', 'description_en',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sliders', 'description_ru',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sliders', 'description_ru',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('sliders', 'description_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('sliders', 'description_uz',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_table('settings',
    sa.Column('address_uz', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_ru', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('telegram', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('about_us',
    sa.Column('body_uz', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_ru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], name=op.f('about_us_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('about_us_pkey'))
    )
    op.create_index(op.f('ix_about_us_id'), 'about_us', ['id'], unique=False)
    # ### end Alembic commands ###
